name: ndxplorer
channels:
  - conda-forge
dependencies:
  - pip
  - qt >=5
  - qtpy
  - pyqt
  - numpy
  - pyyaml
  - pandas
  - pyqtgraph
  - pathlib2
  - typing-extensions
  - qscintilla2
  - scipy
  - guiqwt
